### DISCUSSION TITLE
How to hide join and quit messages

### DISCUSSION THREAD

**Discussion by shahryarjb** [squidowl/halloy#406] [Q&A] [answered]
Hello, how can hid all join and quit messages in a channel?
Thank you

**Comment by casperstorm** [comment, marked as answer]
Take a look at: https://halloy.squidowl.org/configuration/buffer.html#bufferserver_messages-section
Note that this is globally, and not per channel.

```toml
[buffer.server_messages.join]
enabled = false

[buffer.server_messages.quit]
enabled = false
```
