### DISCUSSION TITLE
Can one configure multiple keyboard shortcuts for a single command?

### DISCUSSION THREAD

**Discussion by douglaslassance** [squidowl/halloy#970] [Q&A]
I assume not, since not in the [documentation](https://halloy.chat/configuration/keyboard.html). Something like this would be nice:
```toml
[keyboard]
command_bar = ["alt+k", "ctrl+shift+p"]
```
