### ISSUE TITLE
Feature request: Buffer "workspaces" or grouping

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#153]
I feel the buffer tiles are one of, if not the best, elements of Halloy (easy to arranged, really fluid etc). Only problem is that it is possible to have a nice arrangement of channels you use but then you need to open up a couple more and you have to start closing them to save screen estate or otherwise rearranging stuff (I know there is the really nice "overlay" mode but that is only for a single buffer).

What I'm proposing would be a "workspace switcher" but for the buffers.

So for example:
- Workspace 1 might have 3 buffers arranged in a classic master-stack type layout
- Workspace 2 might have 4 buffers arranged in a grid

Switching could just be done via the existing channel list but with an additional UI element surrounding them to indicate that they are grouped.

Ideally it could be configured via the config file too, something like:

```yaml
workspaces:
  workspace1: 
    channels: "#halloy", "#linux"
    layout: "left", "right"
  workspace2:
    channels: "#git", "#fedora"
    layout: "top", "bottom"
```

(stated with no regard for the `servers: -> channels` options).
