### ISSUE TITLE
Connects to channels before authenticating

### ISSUE THREAD

**Issue by collodrollo** [squidowl/halloy#229]
There are some channels that require authentication to join. #javascript on Libera, for example. These channels will not be joined on halloy startup because nickserv authentication has not occurred by the time attempts to join them have been made.

**Comment by avoidik** [comment]
you could set it as follows:

```
servers:
  libera:
    nickname: user
    nick_password: password 
```
