### ISSUE TITLE
2024.3 release - buffer.server_messages[].exclude are not boolean?

### ISSUE THREAD

**Issue by avoidik** [squidowl/halloy#253]
hello,

I was unable to use default configuration template, it seems all `buffer.server_messages[].exclude` expecting something else than boolean

if I use this config:

```yaml
buffer:
  server_messages:
    join:
      exclude: false
      username_format: Short
    part:
      exclude: false
    quit:
      exclude: false
```

I get this error:

![image](https://github.com/squidowl/halloy/assets/6435932/9aff1621-9154-4fd4-a6a3-7243afa5869d)

it works fine if I use this config with all `exclude` commented out:

```yaml
buffer:
  server_messages:
    join:
      # exclude: false
      username_format: Short
    part:
      # exclude: false
    quit:
      # exclude: false
```
