### ISSUE TITLE
password_file option not working in Flatpak version

### ISSUE THREAD

**Issue by shombando** [squidowl/halloy#321]
Through extended trial and error with @tarkah we discovered that the Flatpak version `halloy 2024.5` is not passing along the password correctly.

This works:
```toml
username = "shom"
password = "hunter2"
```
But storing the password in a file does not work:
```sh
echo "hunter2" > ./passwd
```
```toml
username = "shom"
password_file = "./passwd"
```
This is also true when using a full path `"/home/shom/.var/app/org.squidowl.halloy/config/halloy/passwd"`

The same config file works fine with `halloy 2024.5 (cc8e287)`. 

---
`RUST_LOG=trace ~/.local/share/flatpak/exports/bin/org.squidowl.halloy`: [Log](https://0x0.st/Xii3.txt)
What the interface shows: [screesnshot](https://0x0.st/XiiQ.png)
`config.toml`: [full config file](https://0x0.st/Xi-i.txt)
