### ISSUE TITLE
Connection to Quakenet servers fails

### ISSUE THREAD

**Issue by z0ph** [squidowl/halloy#456]
Hey folks,

I'm trying halloy for the first time and I'm stuck connecting to Quakenet Servers. I saw a closed issue (#171) talking about quakenet related issue, but I can't see related option?

The issue is `err 60`  while connecting.

![CleanShot 2024-08-01 at 18 46 50@2x](https://github.com/user-attachments/assets/029c0204-cb9f-4717-bcc5-90ca5c6c987f)

## Config

```
[servers.quakenet]
nickname = "zoph"
server = "stockholm.se.quakenet.org"
channels = ["#test"]

[buffer.channel.topic]
enabled = true
```

Thanks for your help
Cheers,
zoph

**Comment by andymandias** [comment]
I believe QuakeNet does not support TLS (which is enabled by default).  Please try changing the `[servers.quakenet]` settings to
```toml
[servers.quakenet]
nickname = "zoph"
server = "stockholm.se.quakenet.org"
use_tls = false
channels = ["#test"]
```
