### ISSUE TITLE
Unable to connect to IRC server

### ISSUE THREAD

**Issue by astronaut954** [squidowl/halloy#458]
Tried reaching the #halloy channel but couldn't get the proper help. I'm trying to connect to cgpeers IRC server, but it just won't let me in. Here is the config:

```
[servers.cgpeers]
use_tls = false
dangerously_accept_invalid_certs = true
server = "irc.cgpersia.com"
nickname = "astronaut954"
username = "astronaut954"
port = 6697
channels = ["#cg"]
```

When "use_tls" is false I get this error: 
`connection to server lost (An existing connection was forcibly closed by the remote host. (os error 10054))`

And when "use_tls" is true I get this other error:
`connection to server failed (a TLS error occured: io error: received fatal alert: HandshakeFailure)`

I could connect to the cgpeers server using HexChat, I just had to disable the option "Use SSL for all the servers on this network". Do you have any idea what could be happening?

**Comment by casperstorm** [comment]
Use port `6667`, and you can connect:

```toml
[servers.cgpeers]
use_tls = false
dangerously_accept_invalid_certs = true
server = "irc.cgpersia.com"
nickname = "astronaut954"
port = 6667
channels = ["#cg"]
```
