### ISSUE TITLE
permit relative path or same-directory search for nick_password_file

### ISSUE THREAD

**Issue by dmd** [squidowl/halloy#499]
- I keep all my config files in a git repo. 
- I use the `password_file` functionality
- On one of the computers I want to use halloy on, my username is different from the others (at work it's my last name instead of my initials)

I can't use halloy on the work computer, because `password_file` [has to be an absolute path](https://github.com/squidowl/halloy/pull/381).

If shell expansion would be a lot of work, at least allow relative path - or even no path at all (i.e., if there is no path, assume the file is in the same directory as `config.toml`?

**Comment by o-alquimista** [comment]
Path relative to the `config.toml` directory would be nice.

```toml
[servers.liberachat.sasl.plain]
username = "john_doe"
password_file = "passwords/liberachat"

[servers.oftc.sasl.external]
cert = "certs/oftc.cer"
key = "certs/oftc.key"
```
