### ISSUE TITLE
password_file in sasl.plain not working (flatpak)

### ISSUE THREAD

**Issue by o-alquimista** [squidowl/halloy#512]
```toml
[servers.liberachat.sasl.plain]
username = "myuser"
password_file = "/home/dsilva/.var/app/org.squidowl.halloy/config/halloy/passwords/liberachat"
```

Things I've done:
- Knowing that flatpak can create permission issues ([see my latest discussion](https://github.com/squidowl/halloy/discussions/511)), I've made sure that the `passwords` folder is in the same directory as `config.toml`.
- I've checked for newlines and other unintended characters in the file — it looks correct.

Still, authentication fails.
```
15:33  ∙ connecting to server...
15:33  ∙ connected
15:33 *** Checking Ident
15:33 *** Looking up your hostname...
15:33 *** Couldn't look up your hostname
15:33 *** No Ident response
15:33 SASL authentication failed
15:33 Welcome to the Libera.Chat Internet Relay Chat Network
```

If I instead use the option `password` and paste the password into `config.toml`, authentication succeeds.
```toml
[servers.liberachat.sasl.plain]
username = "myuser"
password = '''my_password_with_digits_letters_symbols'''
```

Halloy 2024.10 from Flathub (user installation).
