### ISSUE TITLE
Feature request: Display nicknames above message

### ISSUE THREAD

**Issue by robert-groensfeld** [squidowl/halloy#611]
So far it is possible to align nicknames left and right in the configuration:
```toml
[buffer.nickname]
alignment = "right"
```
Additionally, I would like to have an option to display nicknames and times above the original message and save some vertical space:

```toml
[buffer.nickname]
position = "top"
position = "left"
```

![image](https://github.com/user-attachments/assets/1b07cb6b-d880-4347-9296-94684d1aaf6e)

I'd be willing to try to implement this if you can give me some pointers.
