### ISSUE TITLE
support reading passwords using org.freedesktop.secrets spec (a.k.a, from keyring)

### ISSUE THREAD

**Issue by Avinash-Bhat** [squidowl/halloy#681]
_(Storing passwords in plain text may not be a good idea.)_

It would be quite easier if the app reads from the keyring (https://www.freedesktop.org/wiki/Specifications/secret-storage-spec/) using config like:

```toml
[servers.liberachat.sasl.plain]
username = "foobar"
use_keyring = true
```

If the keyring doesn't have the password, then the password can be taken from the user and stored in the keyring.

crate [libsecret](https://crates.io/crates/libsecret) can be used for this purpose
