### ISSUE TITLE
Themes not dynamically switching on MacOS Sequoia 15.3.1

### ISSUE THREAD

**Issue by fluteds** [squidowl/halloy#796]
When setting `theme = { light = "rose-pine-dawn", dark = "rose-pine" }` in `config.toml`, Halloy does not switch themes based on macOS appearance settings. Instead, it stays on the default dark theme even if you set the default dynamic themes eg. `theme = { light = "ferra-light", dark = "ferra" }`.

**Expected Behavior:** 

Halloy should automatically switch between the light and dark themes based on macOS’s appearance settings.  

**Actual Behavior:**  

- Halloy does not switch themes dynamically.  
- Manually setting `theme = "rose-pine"` or `theme = "rose-pine-dawn"` works, but automatic switching does not.  

**Steps to Reproduce:**  

1. Set the following in `~/.config/halloy/config.toml` at top level:

   ```toml
   theme = { light = "rose-pine-dawn", dark = "rose-pine" } # Or use the default theme
   ```  
2. Save and reload config.  
3. Switch between Light and Dark Mode in macOS System Settings → Appearance.  
4. Observe that Halloy does not switch themes automatically.  

**Environment:**  

- **OS:** macOS  Sequoia 15.3.1
- **Halloy version:** 2025.2
- **Installation method:** Homebrew

```toml
# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

theme = { light = "rose-pine-dawn", dark = "rose-pine" }
scale_factor = 1.2

[font]
size = 14
# ...
```
