### ISSUE TITLE
action upon double click in nicklist?

### ISSUE THREAD

**Issue by 0ther0ne** [squidowl/halloy#801]
something like:

```
[buffer.channel.nicklist]
double_click = "query"

```

to change behavior from _mention_ the selected user to _open a query_ with selected user

**Comment by joehonkey** [comment]
Are you specifically talking about when you 'click' a username to open a query rather than clicking a username and it goes to the 'send message' buffer?

**Comment by 0ther0ne** [comment]
@joehonkey exactly

**Comment by casperstorm** [comment]
I'll grab this.

**Comment by casperstorm** [comment]
This is done now and will be released along with the next public version.
The configuration looks like this:

```toml
[buffer.nickname]
click = { interaction = "single-click", action = "insert-nickname" }

[buffer.channel.nicklist]
click = { interaction = "double-click", action = "open-query" }
```
