### ISSUE TITLE
[Feature Request] tab completion for / commands

### ISSUE THREAD

**Issue by ndrew222** [squidowl/halloy#910]
I see that when you type `/`, a completion menu pops up. It would be great if you could press `Tab` to access the suggestions.

Even better would be to add subcommand completion, but I'm not sure how that would be implemented

**Comment by ndrew222** [comment]
Oh! I was not able to see that because the highlighted entry is so barely highlighted in my current theme lmao
Thanks

**Comment by ndrew222** [comment]
do you know which parameter in the theme I should change for the command highlight?

**Comment by c-alpha** [comment]
I'd like to see this happen, too.

To my experience, there are two styles for choosing completion candidates from a tooltip or pop-up:

- TAB cycles through the candidates, RET inserts the candidate
- arrow up/down selects the candidate, TAB inserts it

In that light, a new configuration option would probably be needed to switch between the two.

For the sake of example:
```toml
# Type: string
# Values: "enter", "tab"
# Default: "enter"

[buffer.text_input.autocomplete]
insert_key = "enter"
```

**Comment by c-alpha** [comment]
It would also seem useful to me, if it were possible to turn off the wrap-around between completion candidates, i.e. so that it stops when the first or last candidate is reached.

For instance:
```toml
# Type: boolean
# Values: true, false
# Default: true

[buffer.text_input.autocomplete]
cycle = true
```
