### ISSUE TITLE
buffer = "replace-pane" not working

### ISSUE THREAD

**Issue by devantoine** [squidowl/halloy#911]
Hello,

I had Halloy configured to replace the current pane with the new buffer I clicked on in the side bar, and it was working fine.

Now, since latest update (2025.4 on MacOS), it doesn't work anymore.

Reading through the doc it seems that the property's name has been changed (can't remember what it was before I made the change but I was definitely not `buffer`).

So, I tried the following configuration:

```
[sidebar]
buffer = "replace-pane"
```

But when I click on a channel name in the sidebar it still opens a new pane.

The doc being confusing between the use of `sidebar` and `action.sidebar`, I tried the following configuration too:

```
[action.sidebar]
buffer = "replace-pane"
```

But still without any success.

Am I missing something or is this a bug?

**Comment by casperstorm** [comment]
```toml
[actions.sidebar]
buffer = "replace-pane"

```
This works for me, but you might need to reboot Halloy. Have you tried that?

**Comment by casperstorm** [comment]
@andymandias Could you take a look if theres anything fishy going on in the change?

**Comment by andymandias** [comment]
I use this setting and haven't had any issue with it.  I see the used setting is quoted as `[action.sidebar]` when it should be `[actions.sidebar]` (with an s), so maybe that's it?

**Comment by gamayagama** [comment]
None of the actions seem to be working with "replace-pane" at the moment from my testing. 
I have the following in my config, yet anything I click is opened in a new pane.

```TOML
[actions.sidebar]
buffer = "replace-pane"

[actions.buffer]
message_user = "replace-pane"
message_channel = "replace-pane"
local = "replace-pane"
click_username = "replace-pane"
click_highlight = "replace-pane"
click_channel_name = "replace-pane"
```
