### ISSUE TITLE
[Feature Request] CTRL + CMD + F to toggle Fullscreen

### ISSUE THREAD

**Issue by y24o2** [squidowl/halloy#958]
Hallo,

I think it would be great, if the fullscreen mode is to change with macOS default hotkey 
"^ ⌘ F"

Thank you

**Comment by KaiKorla** [comment]
Hi,

you could use a workaround (for now) by adding

```toml
[keyboard]
toggle_fullscreen = "ctrl+command+f"
```

in your configuration.

regards
Kai
