### ISSUE TITLE
have preview be able to use an allowlist of url patterns

### ISSUE THREAD

**Issue by Summertime** [squidowl/halloy#992]
e.g.
```toml
[preview]
    enabled = [
        "*://github.com/*",
        "*://imgur.com/*",
        # etc
    ]
```

I think this would be a good balance between having previews but not having major privacy issues with random URLs
